apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: app-secrets
  namespace: marketing
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: "${CSI_CLIENT_ID}"
    keyvaultName: "${KEY_VAULT_NAME}"
    tenantId: "${KEY_VAULT_TENANT_ID}"
    objects: |
      array:
        - |
          objectName: redis-connection-string
          objectType: secret
        - |
          objectName: db-connection-string
          objectType: secret
        - |
          objectName: marketing-api-base-url
          objectType: secret
  secretObjects:
    - secretName: app-secrets
      type: Opaque
      data:
        - objectName: redis-connection-string
          key: REDIS_CONNECTION_STRING
        - objectName: db-connection-string
          key: DB_CONNECTION_STRING
        - objectName: marketing-api-base-url
          key: MarketingApi__BaseUrl
